services:
  db:
    image: postgres:15-alpine
    container_name: vic-pec-db
    restart: always
    environment:
      POSTGRES_USER: vic-pec
      POSTGRES_PASSWORD: vic-pec
      POSTGRES_DB: vic_pec_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: vic-pec-pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@vicpec.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - db

volumes:
  postgres_data: